### ISSUE TITLE
Stuck on "fetching components from Storybook" anytime i press "manage links" in zeplin.

### ISSUE THREAD

**Issue by Etzix** [zeplin/storybook-zeplin#70]
Storybook v 6.5.10

Storybook-zeplin v 1.7.3

First time i enter the link to our storybook site the fetching works fine, but anytime i press "manage links" in zeplin, i get stuck on this page infintely:
![image](https://user-images.githubusercontent.com/31126885/207572740-744103c3-633b-4a6f-bb4e-fa3a7bc2d4e1.png)

Console only shows a "too many requests" error for a csp violation, but i doubt that is related.

Edit:

Our storybook is only accessible with a VPN , if that info helps :)

**Comment by bedirhankaradogan** [comment]
If your Storybook is behind VPN then you must be connected to the VPN while trying to access your stories over Zeplin. Could you give that a try?

**Comment by Etzix** [comment]
> 

Yes i'm behind the same VPN, i still get this issue.

**Comment by bedirhankaradogan** [comment]
Alright then, are you able to access the Storybook instance URL in a new browser window and see your stories with no issue?

**Comment by Etzix** [comment]
> Alright then, are you able to access the Storybook instance URL in a new browser window and see your stories with no issue?

Sorry, not sure what you mean. I'm able to access Storybook, and i'm able to see the connected stories in zeplin (see picture). I'm just not able to access the "manage storybook" part of zeplin, where you connect new stories to zeplin components. If i press "Manage storybook" it gets stuck.

![image](https://user-images.githubusercontent.com/31126885/214020667-39e2b0c9-7bb6-42f9-8cb4-5109f30d1f79.png)

**Comment by bedirhankaradogan** [comment]
I meant, when you open your Storybook instance URL (the one you've used while setup) in a new browser tab, can you see that your Storybook is being loaded without any problem?

**Comment by Etzix** [comment]
Yes, it works without any issue.

**Comment by bedirhankaradogan** [comment]
Thanks for the information you've provided. Could you send and email about the issue to support@zeplin.io? So that we can better understand your case.

**Comment by bedirhankaradogan** [comment]
Hey there, we fixed the bug that causes this issue on our side. Could you give another try to see if the problem still persist?

**Comment by Etzix** [comment]
> Hey there, we fixed the bug that causes this issue on our side. Could you give another try to see if the problem still persist?

Hi! just tried it and it seems to be working now. Thank you for being so helpful!
