### ISSUE TITLE
Storybook 8 compatibility

### ISSUE THREAD

**Issue by joevaugh4n** [zeplin/storybook-zeplin#84]
Hey @yuqu! I’m reaching out from the core SB team :)

Storybook 8 (our next major release) is coming soon, and it introduces some breaking changes that your addon might need to account for.

We’ve listed all the key changes in [a new Storybook 8 migration guide](https://storybook.js.org/docs/8.0/addons/addon-migration-guide#key-changes-for-addons), and we’d encourage you to check it out and see if your addon is impacted.

We also have an addons channel in our Discord community, which we’d like to use to better communicate with addon authors in the future. If you’re not part of the server, consider joining [here](https://discord.gg/wMff8FkF) and message me (@joevaugh4n) so that I can give you the addon creator role! If you’re already in the server, please just ping me and I’ll respond to you there.

Thanks for being a part of our addon community!

Joe

**Comment by mmuenker** [comment]
To resolve the dependency issue, we should replace the dependency @storybook/addons and @storybook/api with @storybook/preview-api and @storybook/manager-api.

## @storybook/addons

https://www.npmjs.com/package/@storybook/addons

> The contents of this package have moved to @storybook/preview-api and @storybook/manager-api. Please update your import depending on where are using this API.
> This package will no longer be released as part of the 8.0 release of storybook.

## @storybook/api

https://www.npmjs.com/package/@storybook/api

> The contents of this package have moved to @storybook/manager-api. Please update your import.
> This package will no longer be released as part of the 8.0 release of storybook.

**Comment by cengizhanbasak** [comment]
@joevaugh4n @mmuenker Thanks for reaching out.
We've just updated our addon [v3.0](https://github.com/zeplin/storybook-zeplin/releases/tag/v3.0.0) to be compatible with Storybook v8.
